### ISSUE TITLE
Add warning message to inform user that code will be erased

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1018]
[Design shown here](https://www.figma.com/file/tEpo1ZT4O7txFUT2aI0QAM/252-Python-Scratchpad?node-id=89%3A2837)

**Comment by eddybrando** [comment]
@JRussellHuffman, following our discussions, we won't be including the warning notification in the v1 version of the Scratchpad, but we can add this task already to the [Scratchpad v1.1 milestone](https://github.com/Qiskit/platypus/milestone/11).

Also added the "needs information" tag since we will still need to decide on the final approach of the notification (UI and UX).

**Comment by techtolentino** [comment]
@eddybrando @JRussellHuffman 

I was thinking that we decided on this, for now... to count as the _warning notification_ (I'm starting to feel like "warning" isn't the right word... )


![Screen Shot 2022-05-19 at 6 53 33 AM](https://user-images.githubusercontent.com/6276074/169310869-b62e6428-4ab5-4c56-a97b-e593f9453fd1.png)

**Comment by JRussellHuffman** [comment]
@techtolentino is right, for MVP, a note is the extent that which we are notifying users for MVP.

Is this issue for the MVP release, or specifically for the v1.1 release?

**Comment by techtolentino** [comment]
This should be MVP, in my opinion...

**Comment by techtolentino** [comment]
This has already shipped:

![Screen Shot 2022-10-05 at 1 18 53 PM](https://user-images.githubusercontent.com/6276074/194155297-805337f6-90af-483b-a382-160381038a22.png)
