### ISSUE TITLE
[Content] Mathjax problem in QGAN page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1426]
### Where does the issue happen?

https://learn.qiskit.org/course/machine-learning/quantum-generative-adversarial-networks#quantum-19-0

### What is the content issue?

Looks like the equation is being parsed incorrectly:

![Screenshot 2022-08-09 at 10 22 00](https://user-images.githubusercontent.com/36071638/183613732-4f0320c4-403f-45e4-aeb6-b6dce62e3757.png)

**Comment by vabarbosa** [comment]
@frankharkins i just had one question about this...

the problem here looks like it stems from the period at the end of the LaTex (`$$.`):

![image](https://user-images.githubusercontent.com/13156555/183748102-55347268-d377-4d53-aa0b-b915338bd5de.png)

there are two options here:

(1) remove that period

(2) update the converter to  better handle this case

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13156555/183748351-099fc6e4-b62d-4cd6-8b1e-d3b9f85a5ab3.png">

we definitely want make change (2) but i dont know if you want to also make change (1). i.e., does it make sense to have a period at the end of the math equations?

<img width="739" alt="image" src="https://user-images.githubusercontent.com/13156555/183749093-284013d8-a7ed-4c39-999d-04cd8b50650f.png">

**Comment by frankharkins** [comment]
Thanks @vabarbosa! I think the period belongs here because the equation is part of the sentence above
