### ISSUE TITLE
Add static list of curated syllabi to the Classroom view

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1626]
We need to add the curated syllabi to the user account Classroom view:

- use content from @pandasa123
- use `SyllabusCard` components

**Comment by mariacloehb** [comment]
<img width="754" alt="Screenshot 2022-10-24 at 14 19 17" src="https://user-images.githubusercontent.com/89911196/197523966-9fb69e37-fe3f-4f4d-a866-fc704edcb4b3.png">

Good afternoon Team. I was wondering if this is the design you expect to see from this issue. I am a bit uncertain of what to do after filling up the information provided by Sanket, as there was no visual attachments to the issue. I asked Eddy to invite me to the Curated Syllabus project on Figma since I didn't have previous access to it.

If this is the final design, does anyone know where I could find a sample of the final cards? Anywhere they might have been used previously, or a similar version of them.

Thank you :)

**Comment by pandasa123** [comment]
Hey @mariacloehb, sorry about that. Here's how it looks on the [Qiskit.org (and the expected order)](https://github.com/Qiskit/qiskit.org/blob/4ae988d1486079189fbc270be408b5b2633a80c4/components/learn/StartLearningSection.vue#L389)

The items in here are placeholders:

<img width="722" alt="Screenshot 2022-10-24 at 09 57 45" src="https://user-images.githubusercontent.com/6241840/197543455-ac0b494c-7b1a-413a-a7cd-c105e03ac712.png">

**Comment by techtolentino** [comment]
Merged, thank you @mariacloehb
