### ISSUE TITLE
Bug: Inconsistency between the text and code in Example 3 of Quantum Phase Estimation

### ISSUE THREAD

**Issue by vandieren** [Qiskit/platypus#1712]
### Where does the issue happen?

https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html#3.-Example:-Getting-More-Precision-

### What is the content issue?

The text mentions that the example will illustrate estimating the phase for $\theta=\frac{\pi}{3}$, but the code and the graphical results of the code are for 2pi/3.  The text describing the results again references the results as if they were for pi/3.

**Comment by frankharkins** [comment]
I've just reviewed and I think the existing code is correct. This is because phase estimation finds $\theta$ for the operator $U\vert\psi \rangle =e^{\boldsymbol{2\pi i} \theta }|\psi \rangle$, whereas the phase gate performs  $P\vert 1 \rangle =e^{ i \lambda }| 1 \rangle$.

The code sets $\lambda = 2\pi/3$ to account for the missing factor of $2\pi$, so we have:

$P_{2\pi/3} \vert 1 \rangle =e^{ 2 \pi i \theta }| 1 \rangle$

where $\theta = \pi/3$. This isn't currently explained and should be clarified in the text, code, or both.

**Comment by vandieren** [comment]
Ah, yes.  An explanation of which angle the variable "angle" references will help to improve the exposition.  Thanks for the clarification.
