### ISSUE TITLE
Add translation to Serbian language 

### ISSUE THREAD

**Issue by LukaNedimovic** [Qiskit/platypus#1740]
### Feature description

This is a feature request to add a translation to **Serbian language**.
According to consensus made between people willing to participate, I could serve as the **Translation Lead**.

**Comment by je111ena** [comment]
I would like to contribute.

**Comment by kifumi** [comment]
Hi, thank you so much for expressing your willingness to translate to Serbian!! Could you please follow this translation guideline? https://github.com/Qiskit/platypus/blob/main/TRANSLATING.md  
Cc: @0sophy1  @veenaiyuri @SooluThomas

**Comment by LukaNedimovic** [comment]
Hello, thank you for quick response!
I have opened a PR as described.

**Comment by veenaiyuri** [comment]
Hi @LukaNedimovic @je111ena @pericina ! I appreciate your interest in translating Qiskit into Serbian. The next step would be to have an onboarding meeting with you all. Since many of us are going into our holidays soon, let us meet in January next year. Sasha Lazarevic will also be on this call and I will coordinate with him to send out an invite to you all. Thanks, and looking forward to seeing our Serbian language team next year!

**Comment by LukaNedimovic** [comment]
Thank you, kindly! :)

**Comment by veenaiyuri** [comment]
Hi, I am currently discussing with Sasha on the dates to have an onboarding meeting. Looking forward to talking to you soon!
