### ISSUE TITLE
Update reading time for video pages

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#1830]
At the top of each page in the textbook there is a component for "Reading time" that calculates how long it should take each to complete. This number does not account for video length. For example, on [this page](https://learn.qiskit.org/summer-school/2021/lec1-1-vector-spaces-tensor-products-qubits), the read time is 5 minutes while the video is 54 minutes.

We should update the component to reflect video length on pages that are primarily video.

**Comment by vabarbosa** [comment]
@sriramanved thank you for your interest in this! although, the issue is in the `qiskit.org` it is actually in the incorrect repo (i will initiate transfer of the issue to the [correct repo](https://github.com/Qiskit/platypus)). with that said, the project uses the Mathigon studio framework which is where the reading time calculation is happening. if you are still interested in taking on this issue, you can probably start by figuring out a new/improve reading time calculation that we can use instead of what Mathigon provides. please let me know if you have any questions or need any guidance. thank you again for your interest.

some useful inks:
- [mathigon reading time calculation](https://github.com/mathigon/studio/blob/main/build/markdown/parser.js#L182-L188)
- [textbook reading time usage](https://github.com/Qiskit/platypus/blob/main/server/templates/textbook.pug#L23)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
