### ISSUE TITLE
As a learner, I want to create a user account, so that I can see my learning progress.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#258]
Acceptance criteria:

- [ ] UI Sign-in/sign-up Experience with IBM ID + Mathigon
    - [x] Qiskit/platypus#482
    - [x] Qiskit/platypus#453
    - [x] Qiskit/platypus#821
    - [x] Qiskit/platypus#820
    - [x] Qiskit/platypus#445
    - [x] Qiskit/platypus#819
    - [x] Qiskit/platypus#818
    - [x] Qiskit/platypus#257
    - [x] Qiskit/platypus#817
    - [x] Qiskit/platypus#260
    - [x] Qiskit/platypus#262
    - [x] agree to EULA as a part of sign up Qiskit/platypus#261
    - [x] Qiskit/platypus#267
- [x] User profile that includes
    - [x] ~email~
    - [x] org
    - [x] name
    - [x] Show the user which pages they have previous visited in the textbook
    - [x] Show users what pages they have completed in the textbook
    - [x] Track a users progress in a course
- [ ] Secure/GDPR Compliant 
    - [x] Qiskit/platypus#816 
    - [ ] Qiskit/platypus#261
    - [x] Qiskit/platypus#345
    - [x] Qiskit/platypus#346
    - [x] Qiskit/platypus#271
    - [x] Qiskit/platypus#743
- [x] log out
    - [x] Qiskit/platypus#257

(not acceptance criteria, but still important)
**Note:** Flexible for use cases beyond badges including student profiles, custom problem sets, and more 

Design file for this story: https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=158%3A1941

**Comment by JRussellHuffman** [comment]
Moving the contents of #264 to a comment here, and closing that issue.

Below is a list of all the changes I see, but please feel free to push back, discuss, or recommend others. Grace and I tried to capture everything in a new figma page titled MVP (https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=1114%3A7615) that removes anything that is post-mvp.
Note that we also did usability testing on these pages, and I’m including a few small updates based on the feedback (like changing “Default” to “Learning”).


**Landing page**

1. Update video on the login page. We created a new video that is a little cleaner and includes QML showpieces. Attached below. I’m a little worried about file size, so let’s discuss that if necessary. https://github.com/Qiskit/platypus/issues/265
2. make video take up entire bottom section https://github.com/Qiskit/platypus/issues/265
3. change google icon to a link https://github.com/Qiskit/platypus/issues/266

**EULA page**

1. https://github.com/Qiskit/platypus/issues/267
2. https://github.com/Qiskit/platypus/issues/678 

**Account landing page**  https://github.com/Qiskit/platypus/issues/268

1. update title to “Learning”
2. update text at the top
3. update header text size (changed to h1 and h2 for the breakpoints)
4. remove “groups”
5. remove “badges”
6. remove user title (eg. admin)
7. logout - should it redirect back to the login screen?
8. make text under header be 8 columns wide instead of full width
9. (note: the content of this page is a work in progress in figma, but it should be the course material)

**Privacy page**

1. include privacy statement https://github.com/Qiskit/platypus/issues/269
2. export data https://github.com/Qiskit/platypus/issues/270
3. delete data https://github.com/Qiskit/platypus/issues/271

**Comment by lerongil** [comment]
I see that issue #445 is complete but is not currently accessible when visiting learn.qiskit.org/signin. Is the user icon feature complete or is that still a WIP?

**Comment by techtolentino** [comment]
@lerongil - my instinct says that the user icon work has been sorta lost in the mix, and I say that because I haven't been able to track where the work is/was being done for the past few sprints. (Someone correct me if I'm wrong). 

In my opinion, I think it's worth writing a whole new issue, that will allow us to ship a minimal `UserAccounButton` that would handle cases such as:

- appear in the Textbook beta navigation bar
- if a user is on any Textbook chapter/course page, the dropdown could have a link that takes the user to their account
- the dropdown _could have_ a mix of links such as `Sign in`, `Create an account`, or `Log out` (depending on the user's logged in state)

Just a few thoughts

**Comment by vabarbosa** [comment]
one question i have which i dont recall if we ever discussed is how  should localStorage progress data and db progress data coexist?

do we 

1- just delete/ignore localStorage progress data and if readers are not logged in they get no progress data?
2- keep both (localStorage progress data for logged off reader, db progress data for logged in reader)? 

with option 2, when readers logs on/off, how should differences in the progress data be handled

i- merge localStorage progress data and db progress data 
ii- do not merge and only show localStorage progress data for logged off reader, db progress data for logged in reader

with option i, when merging what should take precedence when there's a conflict?

**Comment by JRussellHuffman** [comment]
I'm not sure how this fits in with the above options, but here is the ideal user experience in my opinion:

The user's progress is tracked even if they don't have an account (presumably localStorage). If we detect they are not logged in, we use the progress tracking as a way to incentivize them to create an account. For example, a tooltip next to the progress tracker that says "Want to store your progress across devices? Create an account". Once they create an account, I'm not sure what is best. We could merge the two and get rid of localStorage, but then if they log out presumably they wouldn't see their progress. I think this might be the best options and we resurface the tooltip message about storing progress.

**Comment by Tansito** [comment]
From what we were discussing with @lerongil today a proposal that we have is the next one:

**Scenario 1: new user**

- A user has progress without an account. When the user creates an account we store the progress from local storage with the purpose that the user maintains its progress.

**Scenario 2: existing user**

- The user logs-in and the data that we use it's only from database.

**Scenario 3: the user has an account but it's not logged**

- The user submit a couple of steps or after some minutes and we show to it a message that if they want to preserve the progress in the future it should logs-in. The user logs-in and we store ONLY the new progression from local storage in the database (in case of conflict the database has the priority).

**Comment by lerongil** [comment]
Hi Team - I will be closing this one out. Fantastic job on the release of user accounts.

**Comment by JRussellHuffman** [comment]
Agreed, great work. Excited that this is officially live :)
