### ISSUE TITLE
User account: Privacy page - export data

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#270]
Design file [here](https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=1114%3A7661)

Notes: 

- need to understand what happens after user exports data
- what should exported data format be?
- any success or error statements

Related: #271 , https://github.com/Qiskit/platypus/issues/264

**Comment by JRussellHuffman** [comment]
Tagging @eddybrando here as well.

I copied over the interactions here into the MVP [figma page](https://www.figma.com/file/SOnOgCGQIWx4oAlSFhIsIX/1972-User-account?node-id=1228%3A7813) that hopefully answers most of this

1. Ideally the data is downloaded directly to their machine (as opposed to an email or otherwise).
2. No preference from the design side. 
3. Yes. I recommend the default carbon toast notifications with Qiskit colors (see figma file above). I included two generic success and failure notifications. Are there more edge cases than these two? Should we say something less generic?

**Comment by Tansito** [comment]
Following my comment from #271 and with the purpose to complete a bit more the information that we have about the export action our current logic let us export from this `user` table:

```
{
    "_id" : ObjectId("xxxxxxxxxxxxxxxxxxxxxxxx"),
    "email" : "user@email.com",
    "previousEmails" : [],
    "firstName" : "David",
    "lastName" : "García Valiñas",
    "type" : "student",
    "country" : "US",
    "picture" : "",
    "oAuthTokens" : [ 
        "ibm:XXXXXXXXXX"
    ],
    "createdAt" : ISODate("2021-12-14T14:19:27.818Z"),
    "updatedAt" : ISODate("2022-01-17T15:50:15.987Z"),
    "__v" : 0,
    "lastOnline" : ISODate("2022-01-17T00:00:00.000Z")
}
```

The next content: ['email', 'previousEmails', 'type', 'country', 'birthday', 'school', 'picture', 'lastOnline']. Additionally to this information is added the progression from the different courses.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
