### ISSUE TITLE
[Content UI] Code formatted as plain text

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#391]
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-demos/bonus-level-make-your-own-puzzles
2. See error near the top where it says "from qiskit_textbook.games import hello_quantum". Should that be contained in a code block?

### What is the current behavior?
text is displayed as plain text on the page

### What is the expected behavior?
the code should be formatted like code

### Screenshots (optional but very helpful)

<img width="763" alt="Screen Shot 2021-11-18 at 10 26 22 AM" src="https://user-images.githubusercontent.com/7633881/142455805-715034c1-bfbc-4e60-8c22-cb2f2b72a25d.png">

### Environment (optional but very helpful)
 - Device: macbook pro and samsung phone
 - OS: android and osx
 - Browser: firefox and brave

probably all environments

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by techtolentino** [comment]
@JRussellHuffman - do you think this could be related?

https://github.com/Qiskit/platypus/issues/357

In this issue ☝, I'm suggesting that design provide guidance on 'syntax highlighting'. Do we have designs for what code syntax highlighting should look like for the following two use cases:


1) at the block level (imagine lines of code that take up the entire width of a paragraph)
```
pip install example
```

2) inline code, for example, `this would be inline` and site right inside some content

**Comment by JRussellHuffman** [comment]
I see the two as separate.

The item described in the issue should just be a bug where text that should be code is formatted like text.

The content of #357 seems like an enhancement to how we render code, which is definitely a good idea, but not really a bug. I'll give some input over in 357, but for this issue, I think the code just needs to be dropped into a code block (instead of plain text).

**Comment by eddybrando** [comment]
**New URL:** https://learn.qiskit.org/course/ch-demos/bonus-level-sandbox#bonus-148-0

@JRussellHuffman, the text `from qiskit_textbook.games import hello_quantum` is indeed being rendered as HTML code:

**Code:**

![Image](https://user-images.githubusercontent.com/22047320/169475317-a4f28045-6b71-46b7-a5f8-9cbabaef8e67.png)

**Screenshot:**

![Image](https://user-images.githubusercontent.com/22047320/169475284-2d9bc299-2040-43f3-8a56-5744bd9cb5b9.png)

But I get the point that it's confusing since it looks too similar to _regular_ text.

To change this, we first need a design of how we want to style text that is inside a `code` tag. But this would be a new feature request and not a bug, unless we have another instance on the Textbook when we display this kind of code (not whole code cells) differently or if we already have a design for it.

**Comment by JRussellHuffman** [comment]
The new URL is broken for me.

It sounds like this might be a content issue. Is the `code` tag different from how code gets rendered inside of a code cell? My assumption is that these snippets of code are supposed to be displayed inside a code block like most other code on most other pages.

**Comment by vabarbosa** [comment]
yes, `code` tag is rendered different from an actual code cell. notebook code cells are meant to be executed, while the `code` tag is in a markdown cell (and not intended for execution). being in a markdown cell, it is being parsed/rendered using the markdown renderer.  i agree these should be inside some code block styling, but as @eddybrando mentioned we'd need a design for  this.

since these `<code>` blocks are not meant to be executed/run, but rather just complement the prose, one option is reusing the current code blocks components styling, but without a `Run` button.

however, i think reusing the same style as the current code block, but without a `Run` button may cause confusion (i.e. falsely thinking something is broken since `Run` button missing)? i

maybe a slightly more different design for these `<code>` blocks so they dont look like plain text but are distinguishable enough them from the executable code cells 🤷🏽‍♂️

**Comment by JRussellHuffman** [comment]
I like this solution. Our standard code block can be pretty heavy, so a slim version that is basically just the cool-gray-10 background for inline code makes sense. 

The example above isn't inline, but do you two think this proposed solution still makes sense?

**Comment by eddybrando** [comment]
> The example above isn't inline, but do you two think this proposed solution still makes sense?

True. For block code GitHub has a similar solution:

```
I'm code.
I'm life.
```

**Comment by vabarbosa** [comment]
so do we agree on something like this (block code vs inline code, using cool-gray-10)

![Image](https://user-images.githubusercontent.com/13156555/183769394-00bc34b9-50b5-4516-a9ae-05d85f3a07cd.png)

**Comment by techtolentino** [comment]
I personally like what you're showing, @vabarbosa 

just noting that on Carbon's website, they use a slight 4px border-radius, and a little bit of left/right padding:

![Screen Shot 2022-08-10 at 5 27 43 AM](https://user-images.githubusercontent.com/6276074/183901615-47815189-ceb0-4025-9c40-e16a597698e4.png)

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
