### ISSUE TITLE
Missing math notations 

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#717]
### Steps to reproduce the problem

1. Go to the [Data Encoding page](https://learn.qiskit.org/course/machine-learning/data-encoding)
2. Scroll down the page and hover over various math notations (light-purple underlined elements in math equations)
3. Compare with the right side utility panel > Math notations

### What is the current behavior?

Some of the math notations with tooltips aren't represented in the utility panel > Math notations table

### What is the expected behavior?

I believe that all highlighted math tooltip/definitions should be shown in the the Math notations table

### Screenshots (optional but very helpful)

![Screen Shot 2022-02-10 at 8 17 43 AM](https://user-images.githubusercontent.com/6276074/153450308-54627065-0a81-45f2-a9b2-963c842e022a.png)

### Environment (optional but very helpful)
 - Device: Macbook pro
 - OS: MacOS
 - Browser: Chrome

**Comment by techtolentino** [comment]
@frankharkins - can you please confirm if this is really a bug, or if this is intended (some formula tooltips _not_ being included in the right side table)

If this is intended, we can close this issue.

Thank you

**Comment by divshacker** [comment]
I don't think it is intended, there should be some more Math notations with their definitions.

**Comment by frankharkins** [comment]
Yes this is intentional! Some variables / symbols have different definitions in different equations, so we only want to display them on the right sidebar if it's true throughout the entire page. E.g. we might have an equation where "x" is "A binary string", but this isn't true for all "x"s in general, so we don't want to display that description on the right sidebar, out of context.

This is actually a feature I requested, if a variable id starts with an underscore, it won't show on the right sidebar.

**Comment by techtolentino** [comment]
Nice, thanks for responding here @frankharkins and thanks for closing the issue 🙏🏽
