### ISSUE TITLE
Wrong description of math notation 

### ISSUE THREAD

**Issue by soumya-s3** [Qiskit/platypus#935]
### Steps to reproduce the problem

1. Click on 'https://learn.qiskit.org/course/ch-states/representing-qubit-states'
2. Go to 'Math notations in right sidebar'

### What is the current behavior?

Math  notation 1 & 0 are decribed as amplitude of |0> & |1> state respectively. But both the states have amplitude 1 and they are plotted as radial vector in bloch sphere of unit radius.

### What is the expected behavior?

Description of these two math notation are not necessary. It can be removed completely. Or it may be described as 
0 -> Classical bit value 0 
1 -> Classical bit value 1

### Screenshots (optional but very helpful)

![issue](https://user-images.githubusercontent.com/64184545/164957786-be3e7903-bded-48f7-8bc6-be7321535658.png)

### Environment (optional but very helpful)
 - Device: Laptop
 - OS: Windows 11
 - Browser: Chrome

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by DeDuckProject** [comment]
The problem is that the definitions of ket 0 and ket 1 are both connected to the 1st and 2nd rows (respectively) of the right (0) ket![image](https://user-images.githubusercontent.com/10045034/167220217-d772f265-1fd9-4674-8257-03b346a973b1.jpeg)

The entire kets should be annotated and then the descriptions would be appropriate.

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
