### ISSUE TITLE
Syllabus link is dead + missing from account

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#946]
### Steps to reproduce the problem

1. Go to [Syllabus](https://learn.qiskit.org/syllabus/YYR-WZ1)
2. See error

### What is the current behavior?

Link is dead, Syllabus is missing from account

### What is the expected behavior?

All users should be able to access the Syllabus without being logged in

### Environment (optional but very helpful)
 - OS: macOS 12.3
 - Browser: Safari 15.4

### Additional context (optional)

Add any other context that could help debug the problem.

**Comment by Tansito** [comment]
Due to #947 we had a problem populating the database for testing and some syllabi were deleted. We applied a database backup recovery but probably we couldn't restore all the information (the users are fine).

As an action point, we disabled by now that script and we will review the process in next sprints 🙏
